### ISSUE TITLE
Handle POST requests for experience/academic/current skill score

### ISSUE THREAD

**Issue by juliawgraham** [CMU-313/fall22-hw3-f4#6]
Acceptance Criteria: 
- The java function (POST) is called correctly.
- The POST request contains the correct data.
- Scores inputted to database match user input in HTML.

Dependencies:
- issue #1 (the frontend needs to have a form that calls the corresponding method in the middleware with the score value(s))
- issue #10, #11, #13 (the backend needs a setter method to that the POST request can call to set the score in the database)

**Comment by Yuqi07** [comment]
Instead POST, PUT is used as it makes more sense in this context.
